Adjust workflow

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -9,7 +9,44 @@ permissions:
   contents: write
 
 jobs:
+  lint-and-quality-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pylint
+          pip install -r requirements.txt
+
+      - name: Check for necessary file
+        run: |
+          if [ ! -f "config.json" ]; then
+            echo "The necessary file config.json is missing. Please add it to the repository."
+            exit 1
+          else
+            echo "config.json found. Proceeding with the pipeline."
+          fi
+
+      - name: Run pylint
+        run: |
+          pylint **/*.py
+
+      - name: SonarQube Scan
+        uses: SonarSource/sonarqube-scan-action@master
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
   build-and-test-python:
+    needs: lint-and-quality-check
     runs-on: ubuntu-latest
     steps:
       - name: Checar o código
@@ -28,7 +65,6 @@ jobs:
       - name: Executar testes unitários
         run: |
           pytest
-    
           
   build-docker:
     runs-on: ubuntu-latest
